version: "3.9"

services:
  app:
    container_name: listEvents_app
    build:
      context: ./
      dockerfile: build/package/app/Dockerfile
    ports:
      - "8900:8900"
    volumes:
      - ./:/go/src/github.com/vinicel/listEvent